name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test

    strategy:
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        go-version:
          - 1.13.x
          - 1.14.x

    runs-on: ${{ matrix.environment }}

    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get github.com/onsi/ginkgo/ginkgo
          ginkgo version

      - name: Test
        run: make test-ci
